services:
  db:
    image: postgres:16.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: proconnect-identite
      POSTGRES_PASSWORD: proconnect-identite
      POSTGRES_DB: proconnect-identite
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.12
    ports:
      - "6379:6379"

  demo-test-client:
    image: ghcr.io/proconnect-gouv/proconnect-test-client@sha256:981b0d80e2bd63d99b8e0af0c09ffef608865277ea48717263f160bd5a93d421 # latest
    environment:
      PORT: 3001
      # default env var can be found at https://github.com/proconnect-gouv/proconnect-test-client/blob/main/.env
      HOST: http://localhost:3001
      PC_CLIENT_ID: client_id
      PC_PROVIDER: http://localhost:3000/
    network_mode: "host"

  standard-client:
    image: ghcr.io/proconnect-gouv/proconnect-test-client@sha256:981b0d80e2bd63d99b8e0af0c09ffef608865277ea48717263f160bd5a93d421 # latest
    environment:
      PORT: 4000
      SITE_TITLE: standard-client
      HOST: http://localhost:4000
      PC_CLIENT_ID: standard_client_id
      PC_CLIENT_SECRET: standard_client_secret
      PC_PROVIDER: http://localhost:3000
      PC_SCOPES: openid email profile organization
      ACR_VALUE_FOR_2FA: "https://proconnect.gouv.fr/assurance/consistency-checked-2fa"
      STYLESHEET_URL:
    network_mode: "host"

  proconnect-federation-client:
    image: ghcr.io/proconnect-gouv/proconnect-test-client@sha256:981b0d80e2bd63d99b8e0af0c09ffef608865277ea48717263f160bd5a93d421 # latest
    environment:
      PORT: 4001
      SITE_TITLE: proconnect-federation-client
      HOST: http://localhost:4001
      PC_CLIENT_ID: proconnect_federation_client_id
      PC_CLIENT_SECRET: proconnect_federation_client_secret
      PC_PROVIDER: http://localhost:3000
      PC_SCOPES: openid uid given_name usual_name email siren siret organizational_unit belonging_population phone chorusdt is_service_public is_public_service
      PC_ID_TOKEN_SIGNED_RESPONSE_ALG: ES256
      PC_USERINFO_SIGNED_RESPONSE_ALG: ES256
      STYLESHEET_URL:
      LOGIN_HINT: unused1@yopmail.com
      ACR_VALUES: eidas1
      EXTRA_PARAM_SP_NAME: ProConnect Test
    network_mode: "host"

  maildev:
    image: maildev/maildev@sha256:180ef51f65eefebb0e7122d8308813c1fd7bff164bc440ce5a3c2feee167a810 # latest
    environment:
      MAILDEV_IP: "::"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:1080/healthz",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    network_mode: "host"

volumes:
  db-data:
